
services:
  database:
    build: 
      context: .
      platforms:
        - linux/amd64  # Force x86-64 platform
    platform: linux/amd64  # Force x86-64 platform
    environment:
      - MSSQL_STARTUP_DELAY=30  # Faster startup for development
      - INSERT_SIMULATED_DATA=true  # Enable simulated data insertion
    volumes:
      # Mount source code for development
      - ./scripts:/scripts
      - ./test/fixtures/init-sql:/docker-entrypoint-initdb.d
      - ./healthcheck.sh:/healthcheck.sh
    # Enable debug logging
    command: ["/docker-entrypoint.sh", "/opt/mssql/bin/sqlservr", "--accept-eula"]
    networks:
      - default
      - proxy

networks:
    default:
    proxy:
      external: true
      name: proxy