on:
  workflow_dispatch:

jobs:
  build-base-images:
    name: "Build Base Images"
    uses: ./.github/workflows/multi-arch-build.yml
    with:
      PUSH: true
      TARGET: "build"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}